basePath: /api/
definitions:
  web.StandartResponse:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
host: localhost:3500
info:
  contact:
    email: tirtanewwhakim22@gmail.com
    name: Tirta Hakim Pambudhi
    url: https://github.com/tirtahakimpambudhi
  description: Managament Todolist with Users auth
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://tos.santoshk.dev
  title: Userd & Todolist Service
  version: 1.0.1
paths:
  /admin/users:
    get:
      description: Responds with the list of all User as JSON By Search
      parameters:
      - description: search users by key
        in: query
        name: search
        required: true
        type: string
      - description: search users by key
        in: query
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/web.StandartResponse'
            type: array
      security:
      - Bearer: []
      summary: Get Users array
      tags:
      - users
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
